spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: Manas@65
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
stripe.key:
  ${STRIPE_KEY}